# Generated by Django 5.1.3 on 2024-11-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0004_feedback_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
