# Generated by Django 5.1.3 on 2024-11-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0008_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
